# Site settings
title: Comox Valley German Language School
email: comoxvalleygermanlanguageschool@gmail.com
sitename: Comox Valley German Language School
description: Learn German
baseurl: '/germanlanguageschool.ca'
url: http://germanlanguageschool.ca

# Build settings
markdown: kramdown
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
